version: '3'
services:
  daap:
    build:  
      context: .
      dockerfile: Dockerfile
    ports: 
      - '3689:3689'
    volumes:
      - '/srv/daap/music:/music'
      - '/srv/daap/config:/config'
      - '/srv/daap/var/log:/var/log'
    tty: true

